strings=input('Write something: ')
print('The third character of this string is: ',strings[0:3]) 
print('Last character of this string is: ',strings[-1])
print('The first five characters of this string are: ',strings[0:5])
print('The last two characters of this string are: ',strings[-2::])
print('The characters of this string with even indices are: ',strings[1::2])
print('The characters of this string with odd indices are: ',strings[0::2])
print('Starting with the second character in the string: ',strings[1])
print('All the characters of the string in reverse order: ',strings[::-1])
print('Every second character of the string in reverse order: ',strings[-1::-2])
#print('Start from last: ',strings[-1:-5:])
print('The length of the given string: ',len(strings))